**Validacion datasets**

In [ ]:
import pandas as pd
import numpy as np
import os
#Carga de datasets a memoria
d_divipola = pd.read_csv("../data/raw/divipola.csv", dtype = str)
d_agrosavia = pd.read_csv("../data/raw/agrosavia.csv", usecols=["Secuencial","Fecha de Análisis","Departamento","Municipio"])
d_eva = pd.read_csv("../data/raw/eva.csv", dtype = str)
#Verificacion Columnas
print("=======================================Info Divipola=======================================")
print(d_divipola.info())
print("=======================================Info Agrosavia=======================================")
print(d_agrosavia.info())
print("=======================================Info eva=======================================")
print(d_eva.info())

=======================================Info Divipola=======================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 7 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Código Departamento                              1122 non-null   object
 1   Nombre Departamento                              1122 non-null   object
 2   Código Municipio                                 1122 non-null   object
 3   Nombre Municipio                                 1122 non-null   object
 4   Tipo: Municipio / Isla / Área no municipalizada  1122 non-null   object
 5   longitud                                         1122 non-null   object
 6   Latitud                                          1122 non-null   object
dtypes: object(7)
memory usage: 61.5+ KB
None
=======================================Info Agrosavia=======================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92738 entries, 0 to 92737
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Secuencial                          92738 non-null  object
 1   Fecha de Análisis                   92738 non-null  object
 2   Departamento                        92738 non-null  object
 3   Municipio                           92736 non-null  object
 4   Cultivo                             92738 non-null  object
 5   Estado                              92738 non-null  object
 6   Tiempo de establecimiento           92738 non-null  object
 7   Topografia                          92738 non-null  object
 8   Drenaje                             92738 non-null  object
 9   Riego                               92738 non-null  object
 10  Fertilizantes aplicados             92738 non-null  object
 11  pH agua:suelo                       92738 non-null  object
 12  Materia organica                    92738 non-null  object
 13  Fósforo Bray II                     92738 non-null  object
 14  Azufre Fosfato monocalcico          92738 non-null  object
 15  Acidez Intercambiable               92738 non-null  object
 16  Aluminio intercambiable             92738 non-null  object
 17  Calcio intercambiable               92738 non-null  object
 18  Magnesio intercambiable             92738 non-null  object
 19  Potasio intercambiable              92738 non-null  object
 20  Sodio intercambiable                92738 non-null  object
 21  capacidad de intercambio cationico  92738 non-null  object
 22  Conductividad electrica             92738 non-null  object
 23  Hierro disponible olsen             92738 non-null  object
 24  Cobre disponible                    92738 non-null  object
 25  Manganeso disponible Olsen          92738 non-null  object
 26  Zinc disponible Olsen               92738 non-null  object
 27  Boro disponible                     92738 non-null  object
 28  Hierro disponible doble acido       92737 non-null  object
 29  Cobre disponible doble acido        92738 non-null  object
 30  Manganeso disponible doble acido    92738 non-null  object
 31  Zinc disponible doble  acido        92738 non-null  object
dtypes: object(32)
memory usage: 22.6+ MB
None
=======================================Info eva=======================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166732 entries, 0 to 166731
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Código Dane departamento       166732 non-null  object
 1   Departamento                   166732 non-null  object
 2   Código Dane municipio          166732 non-null  object
 3   Municipio                      166732 non-null  object
 4   Grupo cultivo                  166732 non-null  object
 5   Subgrupo                       166732 non-null  object
 6   Cultivo                        166732 non-null  object
 7   Desagregación cultivo          166732 non-null  object
 8   Año                            166732 non-null  object
 9   Periodo                        166732 non-null  object
 10  Área sembrada                  166732 non-null  object
 11  Área cosechada                 166732 non-null  object
 12  Producción                     166732 non-null  object
 13  Rendimiento                    166732 non-null  object
 14  Ciclo del cultivo              166732 non-null  object
 15  Estado físico del cultivo      166732 non-null  object
 16  Código del cultivo             166732 non-null  object
 17  Nombre científico del cultivo  166732 non-null  object
dtypes: object(18)
memory usage: 22.9+ MB
None

In [16]:
print("conteo lineas divipola bash")
!wc -l ../data/raw/divipola.csv
print("\nconteo lineas eva bash")
!wc -l ../data/raw/eva.csv
print("\nconteo lineas agrosavia bash")
!wc -l ../data/raw/agrosavia.csv

conteo lineas divipola bash
1123 ../data/raw/divipola.csv

conteo lineas eva bash
166733 ../data/raw/eva.csv

conteo lineas agrosavia bash
92773 ../data/raw/agrosavia.csv

In [22]:
pd.set_option('display.max_columns', None)
print('========================================descripcion divipola========================================')
display(d_divipola.describe())
print('========================================descripcion eva========================================')
display(d_eva.describe())
print('========================================descripcion agrosavia========================================')
display(d_agrosavia.describe())

========================================descripcion divipola========================================

,Código Departamento,Nombre Departamento,Código Municipio,Nombre Municipio,Tipo: Municipio / Isla / Área no municipalizada,longitud,Latitud
count,1122,1122,1122,1122,1122,1122,1122
unique,33,33,1122,1037,3,1121,1122
top,05,ANTIOQUIA,99773,LA UNIÓN,Municipio,"-73,308399","4,446352"
freq,125,125,1,4,1103,2,1

========================================descripcion eva========================================

,Código Dane departamento,Departamento,Código Dane municipio,Municipio,Grupo cultivo,Subgrupo,Cultivo,Desagregación cultivo,Año,Periodo,Área sembrada,Área cosechada,Producción,Rendimiento,Ciclo del cultivo,Estado físico del cultivo,Código del cultivo,Nombre científico del cultivo
count,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732,166732
unique,32,32,1103,1021,8,23,165,194,7,21,11168,10825,23256,2438,2,10,194,158
top,15,Boyacá,41548,La Unión,Frutales,Cereales,Maíz,Yuca consumo en fresco,2025,2024,5.00,0.00,0.00,10.00,Transitorio,En fresco,1081001,Zea mays
freq,17679,17679,478,801,49152,28663,21992,9677,25617,9955,6248,7116,7116,9380,101676,113470,9677,21992

========================================descripcion agrosavia========================================

,Secuencial,Fecha de Análisis,Departamento,Municipio,Cultivo,Estado,Tiempo de establecimiento,Topografia,Drenaje,Riego,Fertilizantes aplicados,pH agua:suelo,Materia organica,Fósforo Bray II,Azufre Fosfato monocalcico,Acidez Intercambiable,Aluminio intercambiable,Calcio intercambiable,Magnesio intercambiable,Potasio intercambiable,Sodio intercambiable,capacidad de intercambio cationico,Conductividad electrica,Hierro disponible olsen,Cobre disponible,Manganeso disponible Olsen,Zinc disponible Olsen,Boro disponible,Hierro disponible doble acido,Cobre disponible doble acido,Manganeso disponible doble acido,Zinc disponible doble acido
count,92738,92738,92738,92736,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92738,92737,92738,92738,92738
unique,92738,2388,33,990,282,4,9,13,6,17,5561,737,11088,19021,13606,6972,6206,13443,8241,2735,2569,14261,3567,36134,7060,11363,8648,1903,3212,1075,2565,1498
top,92738,5/08/2016,CUNDINAMARCA,VILLAVICENCIO,Cacao,Por establecer,De 0 a 1 año,Plano,Buen drenaje,No Tiene,No indica,5.04,1.62,<3.87,ND,ND,ND,<1.12,<0.20,<0.09,<0.14,ND,0.21,ND,<1.00,ND,<1.00,0.11,ND,ND,ND,ND
freq,1,685,14016,2165,11104,33138,35644,30656,49807,41159,50200,538,244,11366,1499,45130,45130,2340,3875,15167,33005,67,1790,5872,13832,5872,19301,1430,87951,87952,87952,87952

In [18]:
#Busqueda de vacios
print('========================================vacios divipola========================================')
display(d_divipola.isna().sum())
print('========================================vacios eva========================================')
display(d_eva.isna().sum())
print('========================================vacios agrosavia========================================')
display(d_agrosavia.isna().sum())

========================================vacios divipola========================================

Código Departamento                                0
Nombre Departamento                                0
Código Municipio                                   0
Nombre Municipio                                   0
Tipo: Municipio / Isla / Área no municipalizada    0
longitud                                           0
Latitud                                            0
dtype: int64

========================================vacios eva========================================

Código Dane departamento         0
Departamento                     0
Código Dane municipio            0
Municipio                        0
Grupo cultivo                    0
Subgrupo                         0
Cultivo                          0
Desagregación cultivo            0
Año                              0
Periodo                          0
Área sembrada                    0
Área cosechada                   0
Producción                       0
Rendimiento                      0
Ciclo del cultivo                0
Estado físico del cultivo        0
Código del cultivo               0
Nombre científico del cultivo    0
dtype: int64

========================================vacios agrosavia========================================

Secuencial                            0
Fecha de Análisis                     0
Departamento                          0
Municipio                             2
Cultivo                               0
Estado                                0
Tiempo de establecimiento             0
Topografia                            0
Drenaje                               0
Riego                                 0
Fertilizantes aplicados               0
pH agua:suelo                         0
Materia organica                      0
Fósforo Bray II                       0
Azufre Fosfato monocalcico            0
Acidez Intercambiable                 0
Aluminio intercambiable               0
Calcio intercambiable                 0
Magnesio intercambiable               0
Potasio intercambiable                0
Sodio intercambiable                  0
capacidad de intercambio cationico    0
Conductividad electrica               0
Hierro disponible olsen               0
Cobre disponible                      0
Manganeso disponible Olsen            0
Zinc disponible Olsen                 0
Boro disponible                       0
Hierro disponible doble acido         1
Cobre disponible doble acido          0
Manganeso disponible doble acido      0
Zinc disponible doble  acido          0
dtype: int64

In [19]:
#Busqueda de nulos
print('========================================nulos divipola========================================')
display(d_divipola.isnull().sum())
print('========================================nulos eva========================================')
display(d_eva.isnull().sum())
print('========================================nulos agrosavia========================================')
display(d_agrosavia.isnull().sum())

========================================nulos divipola========================================

Código Departamento                                0
Nombre Departamento                                0
Código Municipio                                   0
Nombre Municipio                                   0
Tipo: Municipio / Isla / Área no municipalizada    0
longitud                                           0
Latitud                                            0
dtype: int64

========================================nulos eva========================================

Código Dane departamento         0
Departamento                     0
Código Dane municipio            0
Municipio                        0
Grupo cultivo                    0
Subgrupo                         0
Cultivo                          0
Desagregación cultivo            0
Año                              0
Periodo                          0
Área sembrada                    0
Área cosechada                   0
Producción                       0
Rendimiento                      0
Ciclo del cultivo                0
Estado físico del cultivo        0
Código del cultivo               0
Nombre científico del cultivo    0
dtype: int64

========================================nulos agrosavia========================================

Secuencial                            0
Fecha de Análisis                     0
Departamento                          0
Municipio                             2
Cultivo                               0
Estado                                0
Tiempo de establecimiento             0
Topografia                            0
Drenaje                               0
Riego                                 0
Fertilizantes aplicados               0
pH agua:suelo                         0
Materia organica                      0
Fósforo Bray II                       0
Azufre Fosfato monocalcico            0
Acidez Intercambiable                 0
Aluminio intercambiable               0
Calcio intercambiable                 0
Magnesio intercambiable               0
Potasio intercambiable                0
Sodio intercambiable                  0
capacidad de intercambio cationico    0
Conductividad electrica               0
Hierro disponible olsen               0
Cobre disponible                      0
Manganeso disponible Olsen            0
Zinc disponible Olsen                 0
Boro disponible                       0
Hierro disponible doble acido         1
Cobre disponible doble acido          0
Manganeso disponible doble acido      0
Zinc disponible doble  acido          0
dtype: int64

In [ ]:
#ajuste agrosavia
primer_campo = d_agrosavia.columns[0]
p_numerico = pd.to_numeric(d_agrosavia[primer_campo].str.strip(), errors="coerce")
print(p_numerico.isna().sum())

0

In [ ]:
for column in d_agrosavia.columns:
    try:
        issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
    except:
        print('issue', column)

/tmp/ipykernel_454141/2633580868.py:3: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
/tmp/ipykernel_454141/2633580868.py:3: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
/tmp/ipykernel_454141/2633580868.py:3: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
/tmp/ipykernel_454141/2633580868.py:3: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
/tmp/ipykernel_454141/2633580868.py:3: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
/tmp/ipykernel_454141/2633580868.py:3: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
/tmp/ipykernel_454141/2633580868.py:3: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
/tmp/ipykernel_454141/2633580868.py:3: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])

In [32]:
municipios = (
    d_agrosavia["Municipio"]
    .dropna()
    .str.strip()
    .loc[lambda s: s.ne("")]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)